version = "3.9.4"
runner.dialect = scala3
runner.dialectOverride.allowSignificantIndentation = false
runner.dialectOverride.allowQuietSyntax = true

maxColumn = 120
align.preset=some
importSelectors = singleLine
rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
rewrite.trailingCommas.style = "multiple"

docstrings.style = keep

project.excludeFilters = [
  "./generated/.*"
]
